version: "3.8"
services:
  backend:
    image: "alvinabaho/springboot-react-fullstack:29.8.2021.23.41.35"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev