version: "3.8"
services:
  backend:
    image: "alvinabaho/springboot-react-fullstack:4.9.2021.3.10.6"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev