version: "3.8"
services:
  backend:
    image: "alvinabaho/springboot-react-fullstack:5.9.2021.17.1.13"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev